### ISSUE TITLE
Issue with space in value

### ISSUE THREAD

**Issue by brandtdaniels** [luketurner/lpass-env#4]
In my note in last pass I have an environment variable 

`AUTH_SCOPES="openid profile email offline_access crm_api mobile search"`

I get the following error

```
$(lpass-env export env/sprint)
-bash: export: `search"': not a valid identifier
```

Any value with spaces has the same problem

**Comment by brandtdaniels** [comment]
I created an SO post here:

https://stackoverflow.com/questions/58809495/when-exporting-environment-variables-with-spaces-in-value-using-lastpass-bash-sc

**Comment by luketurner** [comment]
Thanks for the issue! And thanks for posting your SO post -- very useful!

It sounds like the problem arises when using the `$(...)` syntax for `lpass export` specifically, right? The `eval` approach described in the SO post seems like a decent workaround.

The security of eval-ing arbitrary code you just downloaded is questionable I suppose, but I can mention it in the README as a more flexible option.

**Comment by luketurner** [comment]
I updated the README. Feel free to reopen the issue if you have additional questions/comments.
